apiVersion: apps/v1
kind: Deployment
metadata:
  name: start
spec:
  selector:
    matchLabels:
      app: start
  replicas: 3
  template:
    metadata:
      labels:
        app: start
    spec:
      containers:
        - name: start
          image: adama93/start
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: postgres
            - name: DB_NAME  # Setting Database name from configMap
              value: employee_db
            - name: DB_USERNAME  # Setting Database username from Secret
              value: admin
            - name: DB_PASSWORD # Setting Database password from Secret
              value: passer123
